apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/description: MongoDB Cluster IP
  name: {{ .Values.SERVICE.NAME }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: mongo
      port: {{ .Values.SERVICE.PORT }}
      protocol: TCP
      targetPort: {{ .Values.STATEFULSET.PORT }}
  selector:
    app: {{ .Values.STATEFULSET.LABEL }}
  type: {{ .Values.SERVICE.TYPE }}