apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.STATEFULSET.LABEL }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.STATEFULSET.REPLICAS }}
  selector:
    matchLabels:
      app: {{ .Values.STATEFULSET.LABEL }}
  serviceName: {{ .Values.SERVICE.NAME }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: {{ .Values.STATEFULSET.LABEL }}
    spec:
      initContainers:
        - name: wait-mongo
          image: {{ .Values.IMAGE.VERSION }}
          command:
            - sh
            - -c
            #- sleep 600
            - "cp /etc/mongo/mongo-keyfile /tmp && chown mongodb:mongodb /tmp/mongo-keyfile && chmod 400 /tmp/mongo-keyfile"
          volumeMounts:
            - name: mongo-keyfile-temp
              mountPath: /tmp
      containers:
        - name: {{ .Values.STATEFULSET.CONTAINER.NAME }}
          imagePullPolicy: {{ .Values.IMAGE.PULL_POLICY }}
          image: {{ .Values.IMAGE.VERSION }}
          args: ["--replSet", "rs0", "--keyFile", "/tmp/mongo-keyfile"]
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}
          volumeMounts:
            - mountPath: {{ .Values.PERSISTENCE.PATH }}
              name: {{ .Values.PERSISTENCE.PVC_NAME }}
            - mountPath: /tmp
              name: mongo-keyfile-temp     
      volumes:
        - name: mongo-keyfile-temp
          emptyDir: {}
        {{ if .Values.STATEFULSET.TOLERATIONS.ENABLED }}
      tolerations:
      - key: {{ .Values.STATEFULSET.TOLERATIONS.KEY }}
        operator: {{ .Values.STATEFULSET.TOLERATIONS.OPERATOR }}
        value: {{ .Values.STATEFULSET.TOLERATIONS.VALUE }}
        effect: {{ .Values.STATEFULSET.TOLERATIONS.EFFECT }}
      {{ end }}
      {{ if .Values.STATEFULSET.NODESELECTOR.ENABLED }}
      nodeSelector:
        {{ .Values.STATEFULSET.NODESELECTOR.KEY }}: {{ .Values.STATEFULSET.NODESELECTOR.VALUE }}
      {{ end }}

  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: {{ .Values.PERSISTENCE.PVC_NAME }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.PERSISTENCE.SIZE }}



