apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  MONGODB_USER: {{ .Values.SECRET.DATABASE.MONGODB_USER | b64enc | quote }}
  MONGODB_PASSWORD: {{ .Values.SECRET.DATABASE.MONGODB_PASSWORD | b64enc | quote }}
  MONGODB_OPTIONS: {{ .Values.SECRET.DATABASE.MONGODB_OPTIONS | b64enc | quote }}
  DB_HOST: {{ .Values.SECRET.DATABASE.DB_HOST | b64enc | quote }}
  DB_PORT: {{ .Values.SECRET.DATABASE.DB_PORT | b64enc | quote }}
  APP_DB: {{ .Values.SECRET.DATABASE.APP_DB | b64enc | quote }}
  JWT_SECRET: {{ .Values.SECRET.JWT.SECRET | b64enc | quote }}
  JWT_EXPIRES: {{ .Values.SECRET.JWT.EXPIRES_IN | b64enc | quote }}
  RDS_HOST: {{ .Values.SECRET.DATABASE.RDS_HOST | b64enc | quote }}
  RDS_PASSWORD: {{ .Values.SECRET.DATABASE.RDS_PASSWORD | b64enc | quote }}
  RDS_DATABASE: {{ .Values.SECRET.DATABASE.RDS_DATABASE | b64enc | quote }}
