name: Dispatch Kubernetes Pipeline

on:
  push:
    branches:
      - main

jobs:
  dispatch_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Multi Stage pipeline
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            await github.repos.createDispatchEvent({
              owner: 'fiap-9soat-snackbar',
              repo: 'snackbar-pipeline',
              event_type: 'infra_commit',
              client_payload: {
                repo_name: 'infra'
              }
            });
